### PR TITLE
sequence mode for PlacementMeshImpl

### LINKED ISSUE #14: setting MTF_SEQUENCE_MODE while using PlacementMeshImpl results in error [low priority]
```
  File "/root/code/src/mesh/mesh_tensorflow/ops.py", line 656, in copy_masters_to_slices
    return mesh_impl.copy_master_to_slice_ops[-1]
AttributeError: 'PlacementMeshImpl' object has no attribute 'copy_master_to_slice_ops'
```

Perhaps sequence mode should be a flag to SimdMeshImpl instead of an environment variable

### PR DESCRIPTION
**Pull request by WuTheFWasThat**
fixes #14, and drastically reduces the memory needed on my host machine

### CODE REVIEW

**Comment by WuTheFWasThat** [comment]
@toponado does this look ok?

**Comment by wintersurvival** [comment]
Could you please explain the meaning of "sequence mode" ?

**Comment by WuTheFWasThat** [comment]
it prevents copying master to slices in parallel, which caused memory issues for larger models, back then

**Comment by wintersurvival** [comment]
> if i remember correctly - it prevents copying master to slices in parallel for all the parameters, which caused memory issues for larger models, back then

Thank you for your reply. Does the master located in cpu ?

**Pull request merged**
